services:
  db:
    image: postgres:17-alpine
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: trailcompass
      POSTGRES_PASSWORD: trailcompass
      POSTGRES_DB: tc_system
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "pgdata:/var/lib/postgresql/data/pgdata:Z"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "tc_system"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    restart: always
    networks:
      - internal-network
  server:
    image: ghcr.io/trailcompass/backend:latest
    environment:
      - DEV=false
      - CONNECTION_STRING=jdbc:postgresql://db:5432/tc_system
      - CONNECTION_USER=trailcompass
      - CONNECTION_PASSWORD=trailcompass
      - PORT=8080
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - "./data:/usr/app/data"
    ports:
      - "8080:8080"
    networks:
      - internal-network
    healthcheck:
      test: ["CMD", "curl","-f","http://localhost:$PORT/health","||","exit","1"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pgdata:
networks:
  internal-network: