version: '3.8'
services:
    db:
        image: postgres:15
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        volumes:
            - postgres-db-volume:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - postgres-db-network
    server:
        build: .
        environment:
          - POSTGRES=db:5432
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
            - 8080:8080
        networks:
            - postgres-db-network

volumes:
    postgres-db-volume:
networks:
    postgres-db-network: